network: 
  value: unet_resnet34_2ch
  type: str

dataset:
  value: seg_2ch
  type: str

loss:
  value: weighted_dice_bce_2ch
  type: str

weighted_dice_bce_2ch:

  weight_1: 
    value: 4.0
    type: float

  weight_2: 
    value: 333.3
    type: float

  weight_3:
    value: 1.0
    type: float

  bce_weight: 
    value: 1.0
    type: float

optimizer: 
  value: adam
  type: str

learning_rate:
  value: 1e-4
  type: float

metrics_logger: 
  value: metrics_logger_2ch
  type: str

batch_size: 
  value: 20
  type: int

epochs: 
  value: 1
  type: int

# IMAGE_SIZE: [224, 224, 3]

# AUGMENTATION: True

# INCLUDE_TOP: False

